version: '3.8'
services:
  zap:
    image: zaproxy/zap-stable
    container_name: zap_mfc
    ports:
      - "8080:8080"
    command:
      - zap.sh
      - -daemon
      - -host
      - "0.0.0.0"
      - -port
      - "8080"
      - -config
      - "api.disablekey=true"
      - -config
      - "api.addrs.addr.name=.*"
      - -config
      - "api.addrs.addr.regex=true"
    volumes:
      - ./reports:/zap/reports
    restart: unless-stopped